interface PlayerData {
  "player": Player,
  "custom": {
    "p_verified": Boolean,
    "p_visitors": Number
  },
  "data":{
    "stats":{
      "wins":Number,
      "crown_wins":Number,
      "damage":Number,
      "assists":Number,
      "matches":Number,
      "chests_broken":Number,
      "crown_pickups":Number,
      "damage_done":Number,
      "kills":Number,
      "fusions":Number,
      "last_rank":Number,
      "revives":Number,
      "time_played":String,
      "solo_crown_wins":Number,
      "squad_crown_wins":Number,
      "solo_last_rank":Number,
      "squad_last_rank":Number,
      "solo_time_played":String,
      "squad_time_played":String,
      "solo_matches":Number,
      "squad_matches":Number,
      "solo_wins":Number,
      "squad_wins":Number,
      "careerbest_fused_to_max":Number,
      "careerbest_chests":Number,
      "careerbest_shockwaved":Number,
      "careerbest_damage_done":Number,
      "careerbest_revealed":Number,
      "careerbest_assists":Number,
      "careerbest_damage_shielded":Number,
      "careerbest_long_range_final_blows":Number,
      "careerbest_short_range_final_blows":Number,
      "careerbest_kills":Number,
      "careerbest_item_fused":Number,
      "careerbest_critical_damage":Number,
      "careerbest_survival_time":String,
      "careerbest_healed":Number,
      "careerbest_revives":Number,
      "careerbest_snare_triggered":Number,
      "careerbest_mines_triggered":Number,
      "weapon_headshot_damage":Number,
      "weapon_body_damage":Number,
      "damage_by_items":Number,
      "avg_kills_per_match":String,
      "avg_dmg_per_kill":String,
      "losses":Number,
      "solo_losses":Number,
      "squad_losses":Number,
      "winrate":String,
      "solo_winrate":String,
      "squad_winrate":String,
      "crown_pick_success_rate":String,
      "kd":String,
      "headshot_accuracy":String
    },
    "weapons":{
      "Dragon Fly":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Mammoth MK1":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "The Ripper":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "D-Tap":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Harpy":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Komodo":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Hexfire":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Riot One":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Salvo EPL":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Skybreaker":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Protocol V":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      }
    },
    "hacks":{
      "Mine":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Slam":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Shockwave":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Wall":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Heal":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Reveal":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Teleport":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Ball":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Invisibility":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Armor":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      },
      "Magnet":{
          "kills":Number,
          "damage":Number,
          "headshot_damage":Number,
          "fusions":Number,
          "hs_accuracy":Number
      }
    }
  }
}

interface Player {
  "p_id": String,
  "p_user": String,
  "p_name": String,
  "p_platform": String
}

export default PlayerData